### ISSUE TITLE
你好，关于android的rtsp录像没有写全吧

### ISSUE THREAD

**Issue by zhu528** [CHRick/ijkplayer#1]

**Comment by CHRick** [comment]
录像是和音视频文件的编码格式有关的，和传输协议应该没有关系，现在你这边是什么问题呢

**Comment by CHRick** [comment]
安卓的录像应该是jni层没有写

**Comment by zhu528** [comment]
我想实现的是rtsp流的录制视频功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月22日(周四) 晚上6:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CHRick/ijkplayer] 你好，关于android的rtsp录像没有写全吧 (#1)




 
录像是和音视频文件的编码格式有关的，和传输协议应该没有关系，现在你这边是什么问题呢

**Comment by zhu528** [comment]
是的，我看一下就这个没有，可否提供一下呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月22日(周四) 晚上6:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CHRick/ijkplayer] 你好，关于android的rtsp录像没有写全吧 (#1)




 
安卓的录像应该是jni层没有写

**Comment by zhu528** [comment]
是的，我看了一下没有这个，可否提供一下呢。我现在遇到的问题是两个视频流，一个可以正常录制一个录制有声音没画面



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月22日(周四) 晚上6:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CHRick/ijkplayer] 你好，关于android的rtsp录像没有写全吧 (#1)




 
安卓的录像应该是jni层没有写

**Comment by zhu528** [comment]
你好，楼主，显示在是否有时间回复一下呢

**Comment by CHRick** [comment]
有声音没画面的视频编码格式知道吗

**Comment by CHRick** [comment]
> 是的，我看了一下没有这个，可否提供一下呢。我现在遇到的问题是两个视频流，一个可以正常录制一个录制有声音没画面
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月22日(周四) 晚上6:21 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [CHRick/ijkplayer] 你好，关于android的rtsp录像没有写全吧 (#1) 安卓的录像应该是jni层没有写 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我不是安卓开发，不会写jni

**Comment by zhu528** [comment]
谢谢，问题已经解决了，是因为一直没有得到关键帧，加了一个关键帧判断就好了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CHRick/ijkplayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CHRick/ijkplayer] 你好，关于android的rtsp录像没有写全吧 (#1)





 
有声音没画面的视频编码格式知道吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
